spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/-------
    username: -------
    password: -------
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false